print("Hello Everybody")
print("Phuriphat")
print("Srikhomkum")
print("Shin")
print("m.6/11")
print("Chonrassadornumrung School")
print("18 February 2004")
print("18 Years")
print("Group A")
print("Kamphaeng Phet")
print("Napa Chonburi")
print("Play Game , Edit Picture , Making BG Effects")
print("Red , Magenta , Blue ,Purple")
#นายภูริพัตร ศรีคมขำ ม.6/11 เลขที่ 32